const ServerConfig = {
  TAVONI_PARSE_APP_ID: "TAVONI_UCZVB5TLA4",
  TAVONI_PARSE_REST_API_KEY: "W34LS89GY7K",
  TAVONI_PARSE_JAVASCRIPT_KEY: "TAVONI_GTM456KILKD32",
  TAVONI_PARSE_MASTER_KEY: "5n84nvuhXrRt2C5L",
  TAVONI_PARSE_DB_URI: "mongodb://localhost:27017/TavoniDB",
  TAVONI_PARSE_SERVER_URI: "http://localhost:1337/parse",
  TAVONI_PARSE_SERVER_PORT: 1337,
  TAVONI_PARSE_MOUNT: "/parse",
  AUTH_WITH_AD: false
}

module.exports = ServerConfig
